version: "3"

services:
  plex:

  overseerr:

  sonarr:

  radarr:

  gluetun:

  qbittorrent:

  plexautolanguages:

  plex-meta-manager:

  jackett:

  prowlarr:

  tautulli:

  watchtower:

  portainer:

volumes:
  portainer_data:
  
